proxy:
  build: proxy
  ports:
    - "8080:8080"
  links:
    - mapfishapp
    - urbanisme
    - header
    - cadastrapp
  environment:
    - XMX=512M
mapfishapp:
  environment:
    - XMX=512M
  build: mapfishapp
cadastrapp:
  build: cadastrapp
urbanisme:
  build: urbanisme
header:
  environment:
    - XMX=512M
  image: georchestra/header
